version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "PhConnector"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1p6qggpofae5g"
s3_prefix = "PhConnector"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

